Use caret versions in package.json
snowcoders/sortier pull request #1233
Opened 2021-05-20 17:51 UTC by TikiTDO

Closes #1231

2021-05-20 17:55 UTC, TikiTDO commented
There's also a couple of outdated packages even after the update. Looks like the git hooks integrator moved up a version, and some typescript type got bumped:

```
└> npm outdated
Package        Current  Wanted  Latest  Location                    Depended by
@types/globby    8.0.0   8.0.0   9.1.0  node_modules/@types/globby  sortier
husky            5.1.3   5.2.0   6.0.0  node_modules/husky          sortier
```

Neither seem super critical, but figured I'd mention it here.

2021-05-21 22:04 UTC, k2snowman69 requested changes

2021-05-21 22:04 UTC, k2snowman69 commented on package.json
> +    "flow-parser": "^0.151.0",
Beta packages are a bit less stable
```suggestion
    "flow-parser": "0.151.0",
```

2021-05-21 22:04 UTC, k2snowman69 commented on package.json
> +    "@snowcoders/renovate-config": "^2.0.3",
Pin all dev dependencies, these aren't shipped so the less unstable the better. See https://docs.renovatebot.com/dependency-pinning/#so-whats-best for details of when to pin and when not to pin

2021-05-22 07:47 UTC, k2snowman69 commented
Just to speed things up and unblock you I've opened https://github.com/snowcoders/sortier/pull/1236

2021-05-22 08:05 UTC, k2snowman69 commented
Just published 3.3.0, let me know how it goes for you

2021-05-22 14:19 UTC, TikiTDO commented
Thanks, I'm out for the long weekend here, but I'll check it out on Tuesday

On Sat., May 22, 2021, 4:05 a.m. k2snowman69, ***@***.***>
wrote:

> Just published 3.3.0, let me know how it goes for you
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/snowcoders/sortier/pull/1233#issuecomment-846372254>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACPUKGUYVBN5DOWXIN4ONLTO5QVBANCNFSM45HRDFBA>
> .
>

2021-05-25 19:34 UTC, TikiTDO commented
New version works like a charm, many thanks

2021-05-25 19:34 UTC, closed without merging